version: '3.8'

services:
  litrevu:
    container_name: litrevu_sqlite_db
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # allows SQLite DB persistence
      - ../data:/usr/src/app/data
    environment:
      - DEBUG=False
